### ISSUE TITLE
[feat] 회원가입 API 구현

### ISSUE THREAD

**Issue by 2hyunjinn** [Festimate/Festimate-SERVER#3]
## 🛠 Issue

회원가입 API 구현

## 📝 To-do

- [x] 닉네임 중복검사
- [x] 닉네임 글자수 검사 (1자 이상, 10자 이내)
- [x] 이름 글자수 검사 (1자 이상, 10자 이내)
- [x] 성별 입력 (남자, 여자 제외 에러 발생)
- [x] 학교 입력 (입력 선택 가능 - 미입력시 '미입력'이라고 뜨도록 설정)
- [x] 키 입력
- [x] mbti 입력 (16가지 제외 에러 발생)
- [x] 내 얼굴상 입력 (8가지 제외 에러 발생)
- [x] 얼굴상 enum
